### User Signup

POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "test3@test.com",
    "password": "Test5566",
    "name": "Test User 3"
}


### User Signin

POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Test1244"
}

### Update User Profile

PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Test1244",
    "name": "Test User14"
}

### Get All Users

GET http://localhost:3000/users